-- MySQL Script generated by MySQL Workbench
-- Fri Sep 13 08:10:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- SchemaCapacitacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Capacitacao` DEFAULT CHARACTER SET utf8 ;
USE `Capacitacao` ;

-- -----------------------------------------------------
-- Table `mydb`.`Instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Capacitacao`.`Instrutor` (
  `idInstrutor` 	INT NOT NULL,
  `Nome` 			VARCHAR(100) NOT NULL,
  `Email` 			VARCHAR(100) NOT NULL,
  `Valor_hora` 		DOUBLE NOT NULL,
  `Certificados` 	VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idInstrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capacitacao`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Capacitacao`.`Curso` (
  `idCurso` 		INT NOT NULL,
  `Nome` 			VARCHAR(100) NOT NULL,
  `Requisito`	 	VARCHAR(100) NOT NULL,
  `Carga_horaria` 	DOUBLE NOT NULL,
  `Preco` 			DOUBLE NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capacitacao`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Capacitacao`.`Turma` (
  `idTurma` 				INT NOT NULL,
  `Carga_horaria` 			DOUBLE NOT NULL,
  `Dtata_inicial` 			DATE NOT NULL,
  `Data_final` 				DATE NOT NULL,
  `Instrutor_idInstrutor` 	INT NOT NULL, -- chave estrangeira
  `Curso_idCurso`		    INT NOT NULL, -- chave estrangeira
PRIMARY KEY 				(`idTurma`, `Instrutor_idInstrutor`, `Curso_idCurso`),
-- INDEX 					`fk_Turma_Instrutor_idx` (`Instrutor_idInstrutor` ASC) VISIBLE,--
-- INDEX 					`fk_Turma_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,--
CONSTRAINT 					`fk_Turma_Instrutor`
FOREIGN KEY 				(`Instrutor_idInstrutor`)
REFERENCES 					`Capacitacao`.`Instrutor` (`idInstrutor`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT 					`fk_Turma_Curso1`
FOREIGN KEY 				(`Curso_idCurso`)
REFERENCES 					`Capacitacao`.`Curso` (`idCurso`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capacitacao`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Capacitacao`.`Aluno` (
  `idAluno` 	INT NOT NULL,
  `Nome`		VARCHAR(100) NOT NULL,
  `CPF` 		VARCHAR(14) NOT NULL,
  `DataNasc` 	DATE NOT NULL,
  `Telefone` 	VARCHAR(15) NOT NULL,
  `Email`		 VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capacitacao`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Capacitacao`.`Matricula` (
  `idMatricula` 		INT NOT NULL,
  `Data_matricula` 		DATE NOT NULL,
  `Aluno_idAluno` 		INT NOT NULL, -- chave estrangeira
  `Turma_idTurma` 		INT NOT NULL,  -- chave estrangeira
  PRIMARY KEY 			(`idMatricula`, `Aluno_idAluno`, `Turma_idTurma`),
 -- INDEX `fk_Matricula_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,--
 -- INDEX `fk_Matricula_Turma1_idx` (`Turma_idTurma` ASC) VISIBLE,--
CONSTRAINT 			`fk_Matricula_Aluno1`
FOREIGN KEY 		(`Aluno_idAluno`)
REFERENCES 			`Capacitacao`.`Aluno` (`idAluno`)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT 			`fk_Matricula_Turma1`
FOREIGN KEY 		(`Turma_idTurma`)
REFERENCES 			`Capacitacao`.`Turma` (`idTurma`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
